const fetch = require('node-fetch');
const { GoogleGenerativeAI } = require("@google/generative-ai");
const dotenv = require("dotenv");

dotenv.config();

class LLMService {
    constructor() {
        this.zhipuKey = process.env.ZHIPU_AI_API_KEY;
        this.geminiKey = process.env.GEMINI_API_KEY;
        this.geminiAI = this.geminiKey ? new GoogleGenerativeAI(this.geminiKey) : null;
    }

    async generateSummary(prompt) {
        // 1. Try GLM (BigModel/Zhipu AI)
        if (this.zhipuKey) {
            try {
                const response = await this.callGLM(prompt);
                if (response) {
                    console.log("[LLM] Summary generated by GLM 4/5.");
                    return response;
                }
            } catch (error) {
                console.warn("[LLM] GLM failed, falling back to Gemini:", error.message);
            }
        }

        // 2. Fallback to Gemini
        if (this.geminiAI) {
            try {
                const response = await this.callGemini(prompt);
                console.log("[LLM] Summary generated by Gemini (Fallback).");
                return response;
            } catch (error) {
                console.error("[LLM] Gemini also failed:", error.message);
            }
        }

        return null;
    }

    async callGLM(prompt) {
        const url = "https://open.bigmodel.cn/api/paas/v4/chat/completions";
        const body = {
            model: process.env.GLM_MODEL || "glm-4", // Use glm-4 as stable, can be overridden to glm-4v etc.
            messages: [
                { role: "user", content: prompt }
            ],
            temperature: 0.7,
            max_tokens: 1024
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${this.zhipuKey}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(body)
        });

        if (!response.ok) {
            const errData = await response.json();
            throw new Error(errData.error?.message || response.statusText);
        }

        const data = await response.json();
        return data.choices[0].message.content.trim();
    }

    async callGemini(prompt) {
        const model = this.geminiAI.getGenerativeModel({ model: "gemini-1.5-flash-latest" });
        const result = await model.generateContent(prompt);
        const response = await result.response;
        return response.text().trim();
    }

    // Check if we are currently falling back to Gemini (low rate limit)
    usingLowRateModel() {
        return !this.zhipuKey;
    }
}

module.exports = new LLMService();
